### ISSUE TITLE
Capture the number of leaves for each MS.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary-data#133]
Let's assign a student to work on this.

**Comment by wlpotter** [comment]
I'm working on a google sheet for this: https://docs.google.com/spreadsheets/d/1fFd1hOAKoK2WeEKhjsISv_gJxWsyaZQUxiIB54YvKV4/edit#gid=0 I will add data from the mss to this sheet

**Comment by wlpotter** [comment]
The google sheet should be ready to go. Categories of work:

1. Records with both encoded extent and regex extracted extent -- verify these are correct (296 records)
2. Records with either encoded extent or regex extracted extent -- verify these are correct ( 211 encoded; 370 extracted)
3. Records with neither encoded nor regex extracted extents -- add based on physical description (324 records)

This last category comes from cases where Wright uses words rather than numerals to describe the extent, or if there are intervening words, e.g. "four paper leaves"

**Comment by wlpotter** [comment]
Student is working on this

**Comment by wlpotter** [comment]
This data has a few for me to review, but is otherwise ready for ingest.

Need also to credit Kurt for his work on it

**Comment by wlpotter** [comment]
Completed; student credited
