### ISSUE TITLE
https://bl.syriac.uk/ms/1153 is missing textCLass?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary-data#1546]
@wlpotter how does this error relate to: https://github.com/srophe/britishLibrary-data/issues/1541

element "profileDesc" incomplete; missing required element "textClass"

**Comment by wlpotter** [comment]
This is not related to #1541 (the taxonomy starts at [line 594](https://github.com/srophe/britishLibrary-data/blob/schema-edits/data/tei/1153.xml#L594)) But may be related to #22. The textClass element we deleted in favor of using the tei:head element with a `listRelation/relation` for the subject classifications in each msDesc or msPart.

If this error is just throwing on this file, it may be that the others still have a textClass element? I think we may not want to require this textClass element, though we should see what the consolidated schema expects

**Comment by dlschwartz** [comment]
This is the only file lacking a textClass. I thought that all the profileDesc elements were supposed to be updated to match file 1.xml. Maybe this one didn't get updated? 

Is there are reason we want a textClass everywhere else but not here?

**Comment by wlpotter** [comment]
I updated in #1541 the tei:taxonomy element since there was variance between how the descendant category and catDesc elements were handled. I updated to match record 1.xml, and did the same process for langUsage as these both should be identical for all records.

I did not touch the textClass element, though, because they are not all identical as they contained the specific association of Wright's classification code(s) with each manuscript and/or part(s). This same data was included in the `//msDesc/head/listRelation/relation` elements (or the `//msPart/head/listRelation/relation`), so we should be fine to remove the tei:textClass records since we have moved its data elsewhere unless we need to retain it to be in conformance with the consolidated schema
