### ISSUE TITLE
Add. 14,658 | https://bl.syriac.uk/ms/426

### ISSUE THREAD

**Issue by xchkong** [srophe/britishLibrary-data#1585]
https://github.com/srophe/britishLibrary-data/blob/main/data/tei/426.xml
[Sorry! I forgot if this is the URL that is asked to be attached here]

①Transliteration Rules: Wright uses **Rās-'ain** throughout Add. 14,658, but the website shows **Ras'ain** in many items. Not sure if it matters (cf. line 171, 204,  212, etc. in XML).

②In Item 12 (Philosophic Discourse), Wright says '**probably** composed by Sergius of Rās-'ain', but it seems the website has directly attributed this to Sergius (cf. line 212 in XML).

③Some italics are not preserved in the website (cf. _de Fato_ in line 299 in XML; Wright, 1157). Not sure if it is because the XML doesn't support typing italicised texts.

**Comment by wlpotter** [comment]
Thanks @xchkong! These are all great questions!

1. For transliteration, yes if you are able please do fix the diacritics. [this page](https://syriaca.org/documentation/wiki.html?wiki-page=/Transliteration-and-Vocalization-Standards&wiki-uri=https://github.com/srophe/syriaca-data/wiki) will have many of the characters you need for doing so
2. For the "probably composed by..." we do want to include the attribution to Sergius as an author element; however, we would want to include in a note element Wright's uncertainty, i.e.: `<note>Probably composed by Sergius of Rās-'ain</note>`
3. On italics, one of the distinctions between XML and HTML is that XML is interested in the meaning of the marked-up text while HTML is interested in the display. So for cases where Wright has italicized text, we'd want to know if that is because it is a title or for some other purpose. In this case, _de Fato_ is a title, so we would wrap it in a `<ref>` element
