### ISSUE TITLE
Add. 17,248 | https://bl.syriac.uk/ms/1040

### ISSUE THREAD

**Issue by Frvarghese** [srophe/britishLibrary-data#1600]
The sentence structure of the Syriac text in Addition 2 is shuffled.

**Comment by Frvarghese** [comment]
At line 114 in xml - The title "The Hymns of Severus" is marked as defective. This could possibly be because one of the hymns (The Resurrection) is actually marked by Wright as imperfect. And, the mention of folio for this title is just the beginning one (35a). Perhaps we need to add the complete folia beginning 35a and ending at the start of the last hymn (arranged according to the eight tones) 63b.

**Comment by davidamichelson** [comment]
Thank you, you are correct the sentence structure of the Syriac text in Addition 2 is shuffled. This is due to the presence of the word "(sic)" in English/Latin. Please wrap this in a foreign element like this:

```
<foreign xml:lang="en">(sic)</foreign>
```
This will fix the issue.

On the second issue you raise, that is correct, when a subpart is listed as imperfect by Wright, then the parent msItem that contains it is also marked imperfect.

While in the past we did mark the ending folia ranges with @to="", but now that is not required, so adding 35a is sufficient.

Thank you,
Dave
