### ISSUE TITLE
Add. 14,451 | https://bl.syriac.uk/ms/1568 Problem

### ISSUE THREAD

**Issue by YaelNueKr** [srophe/britishLibrary-data#1655]

**Comment by YaelNueKr** [comment]
A few issues: 
1. it's a composite MS, but I can't find its TEI on Github (and to quote from it). 
2. there are details which the editor inserted that are not in wright (such as stains, holes etc).

**Comment by wlpotter** [comment]
Thanks @YaelNueKr ! Yes, for composite manuscripts the file link will be for the containing record, in this case: https://github.com/srophe/britishLibrary-data/blob/main/data/tei/124.xml. Our developer has updated the website so there should now be a GitHub button with the overall file link.

It looks like this is a case where Wright treats in a single entry what we decided to split into multiple msPart elements, especially for f. 88 since it is palimpsest. Could you send some examples of where the XML file has information that does not appear to be from Wright? @davidamichelson and I should confer on this one, I think
