### ISSUE TITLE
Add. 17,231 | https://bl.syriac.uk/ms/1014 Could not tag words as italic

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1656]
Could not tag words as italic. The guidelines note: Wrap the name or word in <foreign> to render it in italics, but I get a validation error: “element foreign missing required attribute”.

[https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/1014.xml#L410](https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/1014.xml#L409)

https://archive.org/details/catalogueofsyria01brituoft/page/298/mode/2up 

<img width="667" alt="points rukkakh and kushshai are more rare" src="https://github.com/srophe/britishLibrary-data/assets/171574893/6f7183f7-16c5-41ae-b8e1-5a56785458af">

**Comment by wlpotter** [comment]
Thanks @bogdg, this is a tricky case. the foreign element requires an attribute for the language, e.g. `<foreign xml:lang="syr">` (this is the source of the validation error you're seeing). However, in this case since it is transliterated Syriac terms we may need to handle differently. @davidamichelson and I will confer and let you know

**Comment by wlpotter** [comment]
@bogdg following up on this, we will leave these words unmarked, since we are treating the transliteration as English words. It is okay that they will not appear in the website in italic font
