### ISSUE TITLE
Question about enumeration of items - Add. 14,583 | https://bl.syriac.uk/ms/319

### ISSUE THREAD

**Issue by edwards9d** [srophe/britishLibrary-data#1680]
In the this file, the introduction is separated out as a separate item and the incipit is included with it. I see the logic of this (Wright says, "The introduction commences thus"). However, he also lists the incipit under chapter 1. So, my question is, how should I enumerate the items? Should I follow what the previous person did with this file (making the introduction a separate item) or should I correct it to Wright (placing the introductory incipit under chapter 1)?

Thanks,
Daniel

**Comment by wlpotter** [comment]
Thanks @edwards9d ! I think in this case we'd keep the introduction as a separate item since Wright includes it in the title of the containing item. I do think we'd want to update the title of item b1 (for "Part I") to include the reference to the introduction: "Part I., in eleven chapters, preceded by a short introduction, showing how the reader should make use of the book". Then the outline of the c-level items can remain the same with the introduction, then chapter 1, etc.

Let me know if that makes sense or if you need me to clarify. Feel free to close this issue otherwise
