### ISSUE TITLE
Add. 12,178 | https://bl.syriac.uk/ms/10 Question about italicising

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1683]
Apologies if I missed this before, but I haven't managed to figure out how to italicise words.

For example, I tried to render the following

<img width="566" alt="image" src="https://github.com/srophe/britishLibrary-data/assets/171574893/64da24c7-7c55-4a9a-bc13-6d37b1e76e79">

using < hi rend="italic" >Syriac Masora< /hi >, but the error I got was: "Element "hi" not allowed here; expected the element end-tag, text or element "bibl", "choice", "date", "foreign", "list", "locus", "note", "p", "persName", "placeName", "ptr", "quote", "ref", "sic", "table" or "title"". I am probably doing something wrong but I am not sure what.

**Comment by wlpotter** [comment]
Thanks @bogdg! If you remember, one of the differences with TEI XML compared to HTML is that we are more interested in tagging the semantics/meaning of a string of text rather than the formatting. So in the HTML we might have multiple types of text display with italics, but in the XML we want to be more specific. Here, for example, I think we would tag this as a ref element with `@type="work"` since it is referring to the conceptual work (or genre of work, perhaps) called the Syriac Masora. cf. https://bl.syriac.uk/documentation/guidelines#worktitles in the Guidelines

So it would be like this: `<ref type="work">Syriac Masora</ref>`. The Website will then know to display this in italics
