### ISSUE TITLE
Add. 12,178 | https://bl.syriac.uk/ms/10 Tagging Syriac as bibliography

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1695]
I came across this situation and I am not entirely sure what to change. The first quote from Psalms is marked as bibl:

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/10.xml#L577

Whereas the following from Ecclesiastes is not:

https://github.com/srophe/britishLibrary-data/blob/7ed9d834c099761265cdcb643468a8d01e06be53/data/tei/10.xml#L578

https://archive.org/details/catalogueofsyria01brituoft/page/104/mode/2up?view=theater

**Comment by wlpotter** [comment]
@bogdg yes, i think these are marked incorrectly. Do they appear to be excerpts from the manuscript? The one from the Psalms appears like it might be? If so, we can use a `<quote xml:lang="syr">` element rather than a bibl.

I am also wondering about the use of bibl to tag the phrase "Ps. cxxii. 2, fol. 140 b". Is this just referencing a location and passage from the manuscript where the quoted Syriac appears?

**Comment by bogdg** [comment]
Just wanted to clarify re "Ps. cxxii. 2, fol. 140 b", would "Ps. cxxii. 2" need to be tagged as bibl? I did tag fol. 140 b as locus.
It is an internal reference, yes.

**Comment by davidamichelson** [comment]
Thank you for catching these @bogdg, here are the changes to make:

1. For the Syriac text please use the quote element with lang="syr" instead of bibl or foreign (see this example https://bl.syriac.uk/documentation/guidelines#quote)
2. For the references to biblical passages, please do find and wrap all of them with the element ref and put the type=work (see here for examples: https://bl.syriac.uk/documentation/guidelines#worktitles). These should not be wrapped as bibl
