### ISSUE TITLE
Listing Question - Add. 14,611 | https://bl.syriac.uk/ms/349

### ISSUE THREAD

**Issue by edwards9d** [srophe/britishLibrary-data#1716]
I am a bit confused about why the contents of this entry are listed in the way they are. It seems that the XML file reproduces the list that Wright mentions near the end of the entry (bottom of the right column on page 826) and has interpreted this as a1. The entry itself, however, is listed as a2. Is this correct? It seems to me to give a false impression of what Wright's entry states.

**Comment by wlpotter** [comment]
I believe what's happening here is that the extracts that are listed near the end of Wright's entry appear on f. 1a, so the encoder moved them up to the top of  the msContents so that it would follow the folio order of the contents (what Wright has first begins on f. 1b).

Wright doesn't appear to consider the contents on f. 1a as important as the rest and so moves them to the bottom of his entry, but since they are extracts from various works, we do consider them full msItems so want them to appear first, to follow folio order
