### ISSUE TITLE
Add. 14614 | https://bl.syriac.uk/ms/354#msPart2 wrong tags

### ISSUE THREAD

**Issue by YaelNueKr** [srophe/britishLibrary-data#1749]
### Problems with Manuscript Contents

<listPerson>
                    <person>
                      <persName>
                        <foreign xml:lang="syr">ܦܠܛ̇ܘܢ</foreign>
                          
                      </persName>
                      <persName>Plato</persName>
                      <note>

Unsure of what to do here.

**Comment by wlpotter** [comment]
You're right that these tags are incorrect. We'd instead want to wrap each instance of a name with a `<persName>` element, supplying the language of that name with the `@xml:lang` attribute. So it would instead look something like:

```
<note>The names cited are—
  <p>
    <persName xml:lang="syr">ܦܠܛ̇ܘܢ</persName>, <persName xml:lang="en">Plato</persName>. <locus from="119a">Fol. 119 a</locus>
  </p>
  <p>
    <persName xml:lang="syr">ܬܐܦܪܣܛܘܣ</persName>, <persName xml:lang="en">Theophrastus</persName>. <locus from="119b">Fol. 119 b</locus>
  </p>
...
</note>
```

Each of the names should go in its own p element, since Wright puts each one in its own paragraph. Let me know if this makes sense or if I can clarify further.
