### ISSUE TITLE
Add. 14,541, foll. 1–10 | https://bl.syriac.uk/ms/269 MsItem question

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1887]
I am not entirely sure why this ms was split up into the first 6 parts rather than items or rather whether that is correct? The first six parts seem to be items rather

https://archive.org/details/catalogueofsyria02brituoft/page/502/mode/1up

**Comment by wlpotter** [comment]
I think this is coming from the physical description Wright gives where he says "They are taken from no less than
five manuscripts of the ix"' cent. ; viz. foil. 1—10; 11—18; 19—24, 27, 28; 25, 26; and 29 — 38.", so we decided to divide these up since they were once distinct codicological units bound together into what is now 14,541
