### ISSUE TITLE
Add. 14,645 | https://bl.syriac.uk/ms/409 Rubric added by editor?

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1898]
I might be mistaken but I could not find this explicit in Wright, if that this the case, shall I delete?

![image](https://github.com/user-attachments/assets/5e8c51a7-2c10-42ff-bf9c-11d46a32fd71)

https://archive.org/details/catalogueofsyria03brituoft/page/1112/mode/1up?view=theater

**Comment by wlpotter** [comment]
It looks like the encoder was trying to infer this from the footnote where Wright says that the subscription (i.e., the final rubric) adds a few words. So the encoder just repeated the rubric Wright gives, substituting ܫܠܡ for ܬܘܒ and adding the phrase Wright indicates.

I think we would want to revert this to use a note with `@type="footnote"` rather than create a final rubric since we can't be sure what that final rubric contains based on Wright's description. So we would remove the finalRubric element and instead change the rubric element to be:

```
<rubric xml:lang="syr">ܬܘܒ ܬܫܥܝܬܐ ܘܣܗܕܘܬܐ ܕܐܒ̈ܗܬܐ ܩ̈ܕܝܫܐ ܘܛܘ̈ܒܬܢܐ: ܗ̇ܢܘܢ ܕܐܬܪܕܦܘ ܡܢ ܒܪ̈ܒܪܝܐ ܒܛܘܪܐ ܩܕܝܫܐ ܕܣܝܢܝ ܘܒܪܐܝܬܘ<note type="footnote" xml:lang="en">The subscription adds: <foreign xml:lang="syr">ܕܗ̣ܝ ܗܝ ܐܠܝܡ</foreign>.</note> ܐܬܟܬ̤ܒܬ ܕܝܢ ܡܢ ܛܘܒܢܐ ܐܡܘܢܝܘܣ ܝܚܝܕܝܐ</rubric>
```
