### ISSUE TITLE
Add. 14,691, foll. 1–109 | https://bl.syriac.uk/ms/550 Listed order question

### ISSUE THREAD

**Issue by bogdg** [srophe/britishLibrary-data#1900]
It seems that the items contained in the second part have been listed first. Just wanted to ask if I should reorder them?

**Comment by wlpotter** [comment]
These are fine as-is. The first three items (a lesson, prayers, and instructions to the priest) are listed by Wright at the end of the entry because they are in a separate hand. However, since they appear on ff. 1-2 we want to list them as the first items, so that the list of the manuscript's contents follow the order of the folios
