### ISSUE TITLE
Add. 14,523, fol. 38, lower text | https://bl.syriac.uk/ms/1565

### ISSUE THREAD

**Issue by evarodrigo** [srophe/britishLibrary-data#1908]
I don't understand the 2 parts of part 7. Part 7_1 is https://archive.org/details/catalogueofsyria01brituoft/page/294/mode/2up?view=theater . What is Part 7_2?

**Comment by wlpotter** [comment]
Thanks @evarodrigo! In general, palimpsested manuscripts get distinct msPart elements for each layer (over text, undertext(s)). This gets more complicated, like in this example, when we already have an msPart because Wright's entry does not cover the entire manuscript. In these cases, we have tried to create msParts within msParts, so we have part 7 which represents fol. 38 as a composite of parts 7_1 (for its upper text) and 7_2 (for its lower text).

With that said, Wright does not give us any information here about the lower text (and only obliquely refers to the upper text because we can look up what Add. 17,135's contents are. This is why we have "unspecified contents" listed for 7_2 since Wright doesn't tell us anything about the undertext's contents
