### ISSUE TITLE
how to cite SMBL

### ISSUE THREAD

**Issue by davidamichelson** [srophe/britishLibrary-data#1930]
“London, BL, Add. 17232” in _Syriac Manuscripts in the British Library_, edited by D. Michelson and W. Potter. Description by William Wright, edited by Maria S. Thomas et al. https://bl.syriac.uk/ms/1015.

This is a mock up (not sure who the peer review editor is)

**Comment by wlpotter** [comment]
Data changes needed for this:

- [x] Add a seriesStmt for SMBL This is https://github.com/srophe/britishLibrary-data/issues/1931
- [x] Change the creator editor for Wright into an author element, so we can then use `//titleStmt/author` for the "Description by". This is https://github.com/srophe/britishLibrary-data/issues/1932
    - The benefit of this is the flexibility for incorporating other catalog info at a later point, e.g. we could say "Description by Rosen and Forschall" 

Do note that some of this will be different than the consolidated schema's titleStmt: https://msdesc.github.io/consolidated-tei-schema/msdesc.html#titlestatement (though we were already out of step there due to the nature of the data and description sources for our project)

**Comment by wlpotter** [comment]
Once data changes are complete, assign https://github.com/srophe/britishLibrary/issues/406 for visualization changes

**Comment by wlpotter** [comment]
Data changes made; app issue ready to go once data gets pulled into development
