### ISSUE TITLE
Locus for top-level msItems

### ISSUE THREAD

**Issue by nathangibson** [srophe/britishLibrary-data#79]
I sometimes don't see a `<locus>` for top-level msItems. Is this our standard practice or should I add the locus even if it encompasses the entire ms? (I don't see anything about this in the manual.)

srophe/britishLibrary-data#75

**Comment by wlpotter** [comment]
@davidamichelson transferring to bl-data repo. Need to check how many top-level (or maybe any) msItem elements lack a child locus. Then add either by hand or by script. Related to #38 and #61 (which might be the same issue...).

What's different here is that we can't auto-generate the attributes. We need either to add by hand or have a script look for the first child to find the starting locus for the containing item.

We should also document our practice(s) here.

**Comment by davidamichelson** [comment]
Yes, let's try a script for this. All MS items with children items should have locus, or inherit a starting locus from the first child item. We will need to be careful about MS items where the contents are not reported in document order by Wright.

**Comment by davidamichelson** [comment]
Test for MS items without children that are also the only MS item in the MS.

**Comment by wlpotter** [comment]
Good news, bad news here. I got a script working that looks at any msItem that does not have a locus element and tries to find one from the first descendant(s). The good news is that it works for approximately 200 items.

The bad news is that it fails for 982, either because the msItem is the only one in the record or because it can't find a locus in the descendants. Now, I am running this across all msItem elements, not just the top-level. Restricting it just to top level items works for about 115 out of 250 instances.

I have the script set up to log errors, so I can take that log and convert it to a CSV for us, or perhaps a student, to work through.

**Comment by wlpotter** [comment]
Run this on the ones that work and then have a student work on a spreadsheet based on the errors.
